# CAN BE DELETED AT NEXT pyregion RELEASE.
# Only fix necessary was listing numpy as a dependency.

package:
  name: pyregion
  version: "{{version}}"

source:
  fn: pyregion-{{version}}.tar.gz
  url: https://pypi.io/packages/source/p/pyregion/pyregion-{{version}}.tar.gz
  md5: {{md5}}
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyregion = pyregion:main
    #
    # Would create an entry point called pyregion that calls pyregion.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - astropy
    - cython
    - setuptools
    - pyparsing !=2.0.0
    - numpy x.x
    - numpy >1.6
    - matplotlib

  run:
    - python
    - astropy
    - pyparsing !=2.0.0
    - numpy x.x
    - numpy >1.6
    - matplotlib

test:
  # Python imports
  imports:
    - pyregion

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pyregion.readthedocs.org/
  license: MIT License
  summary: 'python parser for ds9 region files'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
