# Needs recipe template to avoid import of pytest-capturelog when
# import tests are run.
package:
  name: ccdproc
  version: "{{version}}"

source:
  fn: ccdproc-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/c/ccdproc/ccdproc-{{version}}.tar.gz
  md5: {{md5}}
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ccdproc = ccdproc:main
    #
    # Would create an entry point called ccdproc that calls ccdproc.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - astropy >=1.0
    - numpy
    - scipy
    - astroscrappy
    - reproject

  run:
    - python
    - astropy >=1.0
    - numpy
    - scipy
    - astroscrappy
    - reproject

test:
  # Python imports
  imports:
    - ccdproc
    - ccdproc.tests
    - ccdproc.utils
    - ccdproc.utils.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://ccdproc.readthedocs.org/
  license: BSD
  summary: 'Astropy affiliated package'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
